# Generated by Django 5.2.13 on 2026-04-17 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("destination_url", models.URLField(max_length=2000)),
                ("short_code", models.CharField(max_length=20, unique=True)),
                ("qr_image", models.URLField(blank=True)),
                ("scan_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fg_color", models.CharField(default="#000000", max_length=7)),
                ("bg_color", models.CharField(default="#ffffff", max_length=7)),
            ],
        ),
    ]
